### ISSUE TITLE
maxctl cached results?

### ISSUE THREAD

**Issue by ap1969** [mariadb-corporation/maxscale-docker#11]
Hi,

I'm setting up maxscale with 3 mariadb servers, running on kubernetes.

Once all the services are up and running, it seems to be running OK: "maxctrl list servers" shows the 3 servers running, and one as master.

However, if I delete completely one or two of the servers, and then run "maxctrl list servers" again, the output hasn't changed after 10-15 minutes.

Any thoughts?

Regards,
Andy

**Comment by ap1969** [comment]
Further to this, if I re-start the maxscale container, it then correctly shows 2 servers as down and one as running/master.

**Comment by markus456** [comment]
Please retry this with the latest 2.4 image and see if it still happens. If it does, please open a bug report on the MariaDB Jira under the MaxScale project.

**Comment by achar007** [comment]
@ap1969, have you managed to configure and use MaxScale in Kubernetes? I'm currently working on it as well.
