### ISSUE TITLE
Switching to using Monit means maxscale logs aren't output

### ISSUE THREAD

**Issue by far-blue** [mariadb-corporation/maxscale-docker#33]
Hi all,

I noticed that with the switch to using Monit in the startup script the maxscale log is no longer streamed out of the docker container. This makes the log hard to access as it's also not available via the web ui.

As Monit doesn't appear to have any way of pipelining service logs, may I suggest adding the line `tail -F /var/log/maxscale/maxscale &` just above the `exec` in the startup script? This will output the log, following log rotation, to stdout and will continue to work when the `exec` hands over to Monit.

Happy to submit a PR if this is considered a good idea - possibly even controllable with an env var and an if statement.

**Comment by k3a** [comment]
I think that switching to monit+syslog was a strange, non-standard move.
Most other containers try to provide the core functionality, just like maxscale 2.4 Docker images used to.

Containers itself shouldn't need any auto-healing or log processing - it is normally the job of higher levels (Docker log modules, Kubernetes, Fluentd, Loki, whatever).

This sounds like they are trying to target people running bare-metal database nodes for performance. But it seems strange to me as those people can do "apt-get install maxscale" on their bare metal distro themselves and configure Monit + Syslog there to suit their needs. They don't need MaxScale in a Docker in such setup IMO.

But fortunately we can still run it as before by explicitly specifying `entrypoint` and `cmd` (`cmd` and `args` in Kubernetes):
- `ENTRYPOINT ["docker-entrypoint.sh"]`
- `CMD ["maxscale", "-d", "-U", "maxscale", "-l", "stdout"]`

**Comment by toddstoffel** [comment]
Esa, let's not make any changes here until we sort this with the DBaaS group.

**Comment by mgolisch** [comment]
Any news on this?
Monit and rsyslogd seems both useless in a container only running one thing(maxscale).
Also with the way rsyslogd is configured it the container cant be run as the maxscale user instead of root.
Its really anyoing have to override that in our own image , especialy as none of those changes seem to add any value.
Theres no need for a process supervisor nor a logging daemon.
What exactly was the rationale to implement those changes?

**Comment by ekorh475** [comment]
I suggest making your own customized Dockerfile. We may at some point convert to a more standard style, but there is no consensus on this.
