### ISSUE TITLE
error  : Failed to create directory '/var/lib/maxscale/maxscale.cnf.d': 13, Permission denied

### ISSUE THREAD

**Issue by presnickety3** [mariadb-corporation/maxscale-docker#38]
Hi, I see the following in maxscale.log on the container, running either as rootful or rootless.  I'm running the container as per instructions on the download page, using the standard Maxscale image out of the box.  The problem appears to be directory /var/lib/maxscale is owned by root;

[root@68db2e341598 /]# tail -f /var/log/maxscale/maxscale.log 
MariaDB MaxScale  /var/log/maxscale/maxscale.log  Thu Oct 28 15:04:09 2021
----------------------------------------------------------------------------
2021-10-28 15:04:09   notice : Worker message queue size: 1MiB
2021-10-28 15:04:09   notice : Using up to 9.4GiB of memory for query classifier cache
2021-10-28 15:04:09   notice : syslog logging is enabled.
2021-10-28 15:04:09   notice : maxlog logging is enabled.
2021-10-28 15:04:09   error  : Failed to create directory '/var/lib/maxscale/maxscale.cnf.d': 13, Permission denied
alert  : Can't access '/var/lib/maxscale/maxscale.cnf.d'.: No such file or directory.
2021-10-28 15:04:09   MariaDB MaxScale is shut down.
----------------------------------------------------

[root@dd9db8bffb6c lib]# ls -l 
total 4
drwxr-xr-x 1 maxscale maxscale   58 Sep 22 00:24 alternatives
drwxr-xr-x 1 maxscale maxscale   24 Sep 22 00:24 dbus
drwxr-xr-x 1 maxscale maxscale    6 Jan 19  2021 dhclient
drwxr-xr-x 1 maxscale maxscale  115 Sep 22 00:24 dnf
drwxr-xr-x 1 maxscale maxscale    6 Nov  4  2020 games
drwxr-xr-x 1 maxscale maxscale    6 Feb 12  2021 initramfs
drwxr-xr-x 1 maxscale maxscale    6 Aug 11 01:31 kdump
drwxr-xr-x 1 maxscale maxscale    6 May 16  2020 logrotate
drwxr-xr-x 2 root     root        6 Oct 28 15:11 maxscale
drwxr-xr-x 1 maxscale maxscale    6 Nov  4  2020 misc
drwxr-xr-x 1 maxscale maxscale    6 May 12  2019 os-prober
drwx------ 1 maxscale maxscale    6 Dec  5  2020 portables
drwx------ 1 maxscale maxscale    6 Dec  5  2020 private
drwxr-xr-x 1 maxscale maxscale 4096 Sep 22 00:24 rpm
drwxr-xr-x 1 maxscale maxscale    6 Nov  4  2020 rpm-state
drwx------ 1 maxscale maxscale    6 Jun  2 06:32 rsyslog
drwxr-xr-x 1 maxscale maxscale   17 Sep 22 00:24 selinux
drwxr-xr-x 1 maxscale maxscale   56 Sep 22 00:24 systemd
drwx------ 1 maxscale maxscale    6 Nov 17  2020 tpm
drwxr-xr-x 1 maxscale maxscale   22 Sep 22 00:24 unbound

Could you have a look please?

Thanks.

**Comment by ekorh475** [comment]
This should be fixed in any future images.
