### ISSUE TITLE
[Question]Some images are missing from the DockerHub repository

### ISSUE THREAD

**Issue by gatolynx** [mariadb-corporation/maxscale-docker#42]
Few days ago, I noticed that some images in [the official DockerHub repository](https://hub.docker.com/r/mariadb/maxscale/) have been reorganized.
For example, mariadb/maxscale/2.4 has been removed and mariadb/maxscale/2.4.10-1 has been created instead.
I don't see any public announcement regarding this.

I am concerned that the repositories are being manipulated and reorganized without any announcement from mariadb.

**Comment by lightningspirit** [comment]
Actually I noticed that too today, when redeploying an instance of MaxScale 2.5.

**Comment by ekorh475** [comment]
We may remove images of old (EOL) versions of MaxScale.
