### ISSUE TITLE
Contents of /var/lib/maxscale/ are not chowned to maxscale

### ISSUE THREAD

**Issue by jinnatar** [mariadb-corporation/maxscale-docker#44]
As now twice the UID of the user maxscale has changed, this means any `/var/lib/maxscale/.secrets` etc  stored in persistent storage has become unreadable to maxscale, which causes system failure on startup. Since changing the UID seems to be regular thing, could you please add a `chown -R maxscale:maxscale /var/lib/maxscale` to the entrypoint to ensure crucial items are readable by the image?

**Comment by lcaflc** [comment]
I support this, this is clearly a big issue with current maxscale docker images that just make it unusable curently. System can just crash at any time when there is an update of the container. 
Upgrade of non main version should be safe at all times.

**Comment by ekorh475** [comment]
This should now be resolved and become visible in any future image builds.
