### ISSUE TITLE
issue regarding CVE greater than 7

### ISSUE THREAD

**Issue by ankursrivastva** [mariadb-corporation/maxscale-docker#46]
[Docker_rmrsp-mariadb-maxscale_version-23.02_svc.rmrsp.auto-a_2023-03-09.zip](https://github.com/mariadb-corporation/maxscale-docker/files/10926952/Docker_rmrsp-mariadb-maxscale_version-23.02_svc.rmrsp.auto-a_2023-03-09.zip)

ther are issues related to glibc, dbus, bin utils and bzip and libtasn1 . Those issues are coming under CVE >7 . Please let me know when we can expect those resolutions.

**Comment by ekorh475** [comment]
Unknown, depends on OS image.
